import os
import sys

out=open(sys.argv[1]+'.done/native.xml','w')

out.write('<ROSETTASCRIPTS>\n')
out.write('        <SCOREFXNS>\n')
out.write('        </SCOREFXNS>\n')
out.write('	<RESIDUE_SELECTORS>\n')
out.write('		<Neighborhood name="nbrhood" resnums="'+sys.argv[2]+'-'+sys.argv[3]+'"/>\n')
out.write('		<Not name="others" selector="nbrhood" />\n')
out.write('	</RESIDUE_SELECTORS>\n')
out.write('	<TASKOPERATIONS>\n')
out.write('		<OperateOnResidueSubset name="turn_off_others" selector="others">\n')
out.write('			<PreventRepackingRLT/>\n')
out.write('		</OperateOnResidueSubset>\n')
out.write('		<RestrictToRepacking name="rtrp"/>\n')
out.write('	</TASKOPERATIONS>\n')
out.write('        <FILTERS>\n')
out.write('		<ScoreCutoffFilter name="scofilter" report_residue_pair_energies="1" cutoff="5000000.0" />\n')
out.write('        </FILTERS>\n')
out.write('	<SIMPLE_METRICS>\n')
out.write('	</SIMPLE_METRICS>\n\n')
out.write('        <MOVERS>\n')
out.write('		<FastRelax name="fast_relax" task_operations="rtrp,turn_off_others" relaxscript="rosettacon2018" repeats="2">\n')
out.write('			<MoveMap name="backbone">\n')
out.write('        			<Chain number="1" chi="1" bb="0"/>\n')
out.write('			</MoveMap>\n')
out.write('		</FastRelax>\n')
out.write('        </MOVERS>\n')
out.write('        <APPLY_TO_POSE>\n')
out.write('        </APPLY_TO_POSE>\n')
out.write('        <PROTOCOLS>\n')
out.write('		<Add mover_name="fast_relax"/>\n')
out.write('		<Add filter="scofilter" />\n')
out.write('        </PROTOCOLS>\n')
out.write('</ROSETTASCRIPTS>\n')

out.close()

out=open(sys.argv[1]+'.done/test.xml','w')

out.write('<ROSETTASCRIPTS>\n')
out.write('        <SCOREFXNS>\n')
out.write('        </SCOREFXNS>\n')
out.write('	<RESIDUE_SELECTORS>\n')
out.write('		<Neighborhood name="nbrhood" resnums="'+sys.argv[2]+'-'+sys.argv[3]+'"/>\n')
out.write('		<Not name="others" selector="nbrhood" />\n')
out.write('	</RESIDUE_SELECTORS>\n')
out.write('	<TASKOPERATIONS>\n')
out.write('		<OperateOnResidueSubset name="turn_off_others" selector="others">\n')
out.write('			<PreventRepackingRLT/> \n')
out.write('		</OperateOnResidueSubset>\n')
out.write('		<RestrictToRepacking name="rtrp"/>\n')
out.write('	</TASKOPERATIONS>\n')
out.write('        <FILTERS>\n')
out.write('		<ScoreCutoffFilter name="scofilter" report_residue_pair_energies="1" cutoff="50000000.0" />\n')
out.write('        </FILTERS>\n')
out.write('	<SIMPLE_METRICS>\n')
out.write('	</SIMPLE_METRICS>\n')
out.write('	\n')
out.write('        <MOVERS>\n')
out.write('		<SimpleThreadingMover name="threader" start_position="2" thread_sequence="GKRSNTTGK" pack_neighbors="1" neighbor_dis="10"  pack_rounds="5" />\n')
out.write('		<FastRelax name="fast_relax" task_operations="rtrp,turn_off_others" relaxscript="rosettacon2018" repeats="2">\n')
out.write('			<MoveMap name="backbone">\n')
out.write('				<Span begin="'+sys.argv[2]+'" end="'+sys.argv[3]+'" chi="1" bb="0"/>\n')
out.write('			</MoveMap>\n')
out.write('		</FastRelax>\n')
out.write('        </MOVERS>\n')
out.write('        <APPLY_TO_POSE>\n')
out.write('        </APPLY_TO_POSE>\n')
out.write('        <PROTOCOLS>\n')
out.write('		<Add mover="threader" /> #Add this line\n')
out.write('		<Add mover_name="fast_relax"/>\n')
out.write('		<Add filter="scofilter" />\n')
out.write('        </PROTOCOLS>\n')
out.write('</ROSETTASCRIPTS>')

out.close()
